# Generated by Django 4.1.7 on 2023-09-01 22:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_lancamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
