# Generated by Django 4.1.7 on 2023-09-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_lancamento_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='comissao',
        ),
    ]
