# Generated by Django 4.1.7 on 2023-11-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_categoria_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=24, null=True)),
                ('password', models.CharField(blank=True, max_length=24, null=True)),
                ('api_id', models.CharField(blank=True, max_length=45, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'verbose_name': 'BlingAccount',
            },
        ),
    ]
