# Generated by Django 4.1.7 on 2023-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_alter_configuracaonotafiscal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icms',
            name='cfop_entrada',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icms',
            name='cfop_entrada_ufd',
            field=models.CharField(default=1000, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icms',
            name='cfop_saida',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icms',
            name='cfop_saida_ufd',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
