# Generated by Django 4.1.7 on 2023-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_icms_cfop_entrada_icms_cfop_entrada_ufd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icms',
            old_name='cfop_entrada_ufd',
            new_name='cfop_ufd',
        ),
        migrations.RemoveField(
            model_name='icms',
            name='cfop_saida',
        ),
        migrations.RemoveField(
            model_name='icms',
            name='cfop_saida_ufd',
        ),
        migrations.AddField(
            model_name='icmssn',
            name='cfop',
            field=models.CharField(default=9, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icmssn',
            name='cfop_ufd',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
