# Generated by Django 4.1.7 on 2023-10-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_rename_cfop_entrada_ufd_icms_cfop_ufd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icms',
            old_name='cfop_entrada',
            new_name='cfop',
        ),
    ]
