# Generated by Django 4.1.7 on 2023-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_condicaopagamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentovenda',
            name='orcam_manual',
            field=models.FileField(default=1, upload_to='manual'),
            preserve_default=False,
        ),
    ]
