# Generated by Django 4.1.7 on 2023-09-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_orcamentovenda_orcam_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Aberto'), ('1', 'Faturado'), ('2', 'Cancelado'), ('3', 'Importado por XML')], default='0', max_length=1)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_orcamento', to='vendas.orcamentovenda')),
            ],
            options={
                'verbose_name': 'Multi-Pedidos de Venda',
                'permissions': (('faturar_pedidovenda', 'Pode faturar Pedidos de Venda'),),
            },
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_pedido', to='vendas.grouppedidovenda'),
        ),
    ]
